project_id = "uxrxrsdasgvygoeavozp"

[auth]
rate_limit.email_sent = 100

[functions.admin-users]
verify_jwt = false

[functions.image-to-base64]
verify_jwt = false

[functions.save-api-key]
verify_jwt = false

[functions.get-api-key]
verify_jwt = false

[functions.validate-invite-code]
verify_jwt = false
