project_id = "uxrxrsdasgvygoeavozp"

[functions.admin-users]
verify_jwt = false

[functions.image-to-base64]
verify_jwt = false

[functions.validate-invite-code]
verify_jwt = false

[auth]
rate_limit_email_sent = 10